name: libphonenumber
description: This is a Flutter implementation of libphonenumber. It includes only a few features at the moment, and are added when more functionality is desired.
version: 2.0.0
homepage: https://github.com/emostar/flutter-libphonenumber

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.libphonenumber
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: LibphonenumberPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
