name: libphonenumber
description: This is a Flutter implementation of libphonenumber. It includes only a few features at the moment, and are added when more functionality is desired.
version: 3.0.0
homepage: https://github.com/emostar/flutter-libphonenumber

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.libphonenumber
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: LibphonenumberPlugin

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
